### ISSUE TITLE
(BUG / v1.12-1.1.4) Haunted Buildings no longer generating.

### ISSUE THREAD

**Issue by Vaygrim** [McJty/LostSouls#5]
Minecraft 1.12
Lost Souls v1.12-1.1.4
Lost Cities v1.12-2.0.5
McJtyLib v1.12-2.6.5
Forge v14.23.2.2615
Mod Pack - [https://github.com/Vaygrim/wasted](https://github.com/Vaygrim/wasted)

Currently not getting any Lost Cities buildings generating as being Haunted. Building percentage is set at 80% in the Lost Souls config, you can check my config files for all your mods in the above linked GitHub for the mod pack.

At present this has only been tested under Single Player as I don't want to update my test server until this is resolved. Help?

**Comment by McJty** [comment]
Since when did this start? Also you mean outside I suppose as your haunt chance for inside is set to 0

**Comment by Vaygrim** [comment]
This started on Monday as I went thru and updated a ton of mods. Also yes, this is outside as we've got no buildings generating inside domes. Mallrat208 has done testing with the same updates and configs on his end, and it appears to be working FINE on his end. (Just got this information about 2 minutes ago.) So I'm going to go back and see what is different about my setup.

**Comment by McJty** [comment]
Did you manage to find anything about this? I have no clue what could be wrong on the mods side I'm afraid

**Comment by Vaygrim** [comment]
This was a corrupt / bad configuration file. Finally tracked that down and proved it yesterday afternoon (sorry for late notification.. it's been a whirlwind Sunday)
